name: Build-test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  build:
    name: build and perform test job
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    strategy:
      matrix:
        nodejs: ['22']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nodejs with version ${{ matrix.nodejs }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-nodejs }}
          cache: 'npm'

      - name: Install dependencies from packages.json
        run: npm ci

      - name: Execute tests with code coverage
        run: npx ng test --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Create artifact for code coverage report
        uses: actions/upload-artifact@v4
        with:
            name: Code coverage report
            path: coverage
