name: Frontend CI-CD workflow

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - id: testLocalAction
        uses: ./

      - name: Build, test and scan project with sonarqube
        uses: ./.github/workflows/build-test-quality-scan.yml

      - name: Build and push image to docker hub
        uses: ./.github/workflows/docker-image.yml
