name: Frontend CI-CD workflow

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  set_owner_and_repo:
    runs-on: ubuntu-latest

  build-test-sonarqube:
    uses: ./.github/workflows/build-test-quality-scan.yml@main

  build-push-docker:
    needs: [build-test-sonarqube]
    uses: ./.github/workflows/docker-image.yml@main
