name: Frontend CI-CD workflow

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action

      - name: Build, test and scan project with sonarqube
        uses: ./.github/actions/build-test-scan

      - name: Build and push image to docker hub
        uses: ./.github/actions/docker
